apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lloyd-anvilizer-pvc
  namespace: lloyd-anvilizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
