apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lloyd-anvilizer-storage
  namespace: lloyd-anvilizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
